edition = "2021"
unstable_features = true

group_imports = "StdExternalCrate" # This is unstable
imports_granularity = "Crate" # This is unstable
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
newline_style = "Unix"
tab_spaces = 4
