[package]
name = "day02-cube-conondrum"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indoc = "2"
itertools = "0.12.0"
nom = "7.1.3"
