[package]
name = "day15-lens-lib"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_matches = "1.5.0"
indexmap = "2.1.0"
indoc = "2"
nom = "7.1.3"
